# This is a basic workflow that is manually triggered
name: Sync to Azure DevOps

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Azure DevOps
        run: |
          # Replace with your Azure DevOps repository URL
          # AZURE_REPO_URL="https://msazure.visualstudio.com/DefaultCollection/RedisCache/_git/TestRepository.git"
          git remote add azure https://msazure.visualstudio.com/DefaultCollection/RedisCache/_git/TestRepository.git
          git push azure HEAD:refs/heads/master
